services:
  postgres:
    image: postgres:latest
    container_name: zero-to-hundred-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zero_to_hundred
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zero-to-hundred-backend
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=zero_to_hundred
      - JWT_SECRET=your_jwt_secret
      - PORT=3000
    ports:
      - "3202:3000"
    volumes:
      - ./backend/src:/app/src
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zero-to-hundred-frontend
    depends_on:
      - backend
    ports:
      - "3201:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_API_URL=/api
    command: npm run dev -- --host 0.0.0.0

  nginx:
    image: nginx:latest
    container_name: zero-to-hundred-nginx
    ports:
      - "3200:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
