version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: zero-to-hundred-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zero_to_hundred_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - zero-to-hundred-network-dev

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: zero-to-hundred-backend-dev
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=zero_to_hundred_dev
      - JWT_SECRET=dev_jwt_secret
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - zero-to-hundred-network-dev
    command: npm run start:dev

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: zero-to-hundred-frontend-dev
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - zero-to-hundred-network-dev
    command: npm run dev

networks:
  zero-to-hundred-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
